ktor:
  application:
    modules:
      - "ru.itmo.ApplicationKt.module"
  deployment:
    port: "$SERVER_PORT:5002"

postgres:
  url: "$APP_POSTGRESQL_DATABASE:jdbc:postgresql://127.0.0.1:5432/tasks_db"
  username: "$APP_POSTGRESQL_USER:postgres"
  password: "$APP_POSTGRESQL_PASSWORD:postgres"

kafka:
  url: "$KAFKA_URL:localhost:9092"