global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ktor-user-service:8001']

  - job_name: 'task-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ktor-task-service:8002']

  - job_name: 'project-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ktor-project-service:8003']

  - job_name: 'analytics-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ktor-analytics-service:8004']

  - job_name: 'ktor-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ktor-api-gateway:8050']


  - job_name: 'ktor-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ktor-api-gateway:8050']